apiVersion: apps/v1
kind: Deployment
metadata:
 name: myapp
spec:
 replicas: 2
 selector:
  matchLabels:
   app: argo-web
 template:
  metadata:
    labels:
     app: argo-web
  spec: 
   containers:
   - name: c1
     image: mgk1231/abcd:v17
     imagePullPolicy: Always
     stdin: true
     tty: true